services:
  redis_1:
    image: redis:latest
    container_name: redis_1
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
      - REDIS_PASSWORD=sbsst123414
    command: redis-server --requirepass sbsst123414