name: "deploy"
on:
  push:
    paths:
      - ".github/workflows/**"
      - "back/fly.toml"
      - "back/src/**"
      - "back/build.gradle.kts"
      - "back/settings.gradle.kts"
      - "back/Dockerfile"
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: application-secret.yaml 생성
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YAML }}
        run: echo "$APPLICATION_SECRET" > back/src/main/resources/application-secret.yaml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: back
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
